### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by GrelTheL** [bellexd/bellehook#1]
‎

**Comment by okureta** [comment]
****

**Comment by GrelTheL** [comment]
Yeah

**Comment by okureta** [comment]
haram?

**Comment by bellexd** [comment]
![7C86A023-504B-452D-ABE4-2D8701939EB2](https://user-images.githubusercontent.com/58997254/89722029-1ebda900-d9dc-11ea-8d4e-2d3dcc1bf153.jpeg)
